spring:
  application:
    name: api-gateway

server:
  port: 8999
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8900/eureka}
  instance:
    preferIpAddress: true

