spring:
  application:
    name: billing-services

server:
  port: 0
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8900/eureka}
    fetch-registry: true
    register-with-eureka: true

  instance:
    preferIpAddress: true

