spring:
  application:
    name: coffee-shop-client
server:
  port: 8081
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8900/eureka}
  instance:
    preferIpAddress: true