spring:
  application:
    name: coffee-shop-client
server:
  port: 8081
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8900/eureka}
    fetch-registry: true
    register-with-eureka: true
  instance:
    preferIpAddress: true

feign:
  hystrix:
    enabled: true
