spring:
  cloud:
    config:
      server:
        git:
          uri: git@github.com:bijeshcnair/cloud-configurations.git
          timeout: 10
          username: bijeshcnair@gmail.com
          password: 81DvPi#@B8Rnxms9yTD
          skip-ssl-validation: true
