spring:
  application:
    name: barista-services
server:
  port: 8082
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8900/eureka}

  instance:
    preferIpAddress: true
